### PR TITLE
Add tests for the example KDL files

### PR DESCRIPTION
**Pull request by lilyball**
This PR adds tests for the `examples/*.kdl` files, to ensure they parse and match the expected contents.

I may have gone a little overboard with the tests. I went down a rabbit hole and wrote a Rust macro that parses very-nearly-KDL (main differences for the test files being nodes need to be semicolon-terminated if they don't have children, and a node whose title contains non-identifier characters needs to be quoted). This was because I wanted to compare the parsed contents of the files, not just whether or not they parse at all. Though for `examples/nuget.kdl` I only tested whether or not it parses, since it's large enough that I didn't want to embed a copy of it into the test.

The ci.kdl and nuget.kdl tests currently fail to parse, but the Cargo.kdl test passes.

This PR is based on #4 and #5.

### CODE REVIEW

**Comment by lilyball** [comment]
I assume you don't want to merge this until the tests pass. But I'd like to know if you're comfortable with the macro approach taken in the test, I know it's a little ridiculous.

I think I will split off the first 3 commits into a separate PR though.

**Comment by lilyball** [comment]
I submitted #4 and #5 to cover the first 3 commits here. I can't remove the commits from this PR though or it won't compile.

**Comment by zkat** [comment]
I think I merged things in the wrong order. Sorry! :<

**Comment by lilyball** [comment]
No you were fine. The conflict comes from #3, since it modified a line that shows up in the context of this. I just updated #5 so I'll rebase this on top of that.

**Comment by zkat** [comment]
aaaand we're good! Thanks a bunch for the PRs, and all the help in general. It's so appreciated!

**Comment by lilyball** [comment]
Haha okay, I didn't realize this was going to get merged before we fixed the test failures 😅

**Comment by zkat** [comment]
what? CI said it was passing. *shakes fist at GitHub*

**Comment by lilyball** [comment]
Oh no 😬 I had just force-pushed, so it was still evaluating.

**Comment by lilyball** [comment]
Perhaps the right thing to do right now is just push a quick commit that skips the two tests. I don't remember offhand how to mark a test as skipped though.

**Comment by zkat** [comment]
Eh. We can fix it when we fix it :) You're the only one hacking on this codebase just now, since I'm spending all my time over on the spec. We can skip it later if it turns into a blocker.

**Comment by lilyball** [comment]
Ok fair enough.

**Pull request merged**
