### PR TITLE
rustup miette

### PR DESCRIPTION
**Pull request by CAD97**

### CODE REVIEW

**Comment by zkat** [comment]
did this myself separately (and included it in `kdl@4.4.0`), so closing this out.

**Comment by CAD97** [comment]
Technically since this is a public dependency, it's a breaking/major change. Probably a low impact one, though.

**Comment by zkat** [comment]
The breaking changes in miette are all reporter option-related, not protocol-related, so they won't affect behavior in this case.

**Comment by CAD97** [comment]
It won't effect *behavior*, but it *is* a breaking change (as `miete@4::Diagnostic` is no longer implemented)

**Pull request closed without merging**
