### PR TITLE
Fix formatting when decoration is not present

### PR DESCRIPTION
**Pull request by CAD97**
A lot easier than #55, actually

Includes/closes #53; redoes #49 properly, subsumes/closes #50

cc @cbiffle one last time

### CODE REVIEW

**Comment by zkat** [comment]
@CAD97 looks like you need to stop relying on `"{foo}"` interpolation in `println!()` and you also need to add `Eq` in a couple of places and it's otherwise ok? Do you mind doing those patches too?

**Comment by CAD97** [comment]
@zkat `cargo +1.56 test --all-features` passes locally now

**Comment by zkat** [comment]
looks like the rest is clippy being picky. Do you mind fixing these too so we can get a green CI?

```
error: `format!(..)` appended to existing `String`
  --> src/fmt.rs:12:17
   |
12 |                 result.push_str(&format!("{:indent$}{}\n", "", trimmed, indent = indent));
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::format-push-string` implied by `-D warnings`
   = help: consider using `write!` to avoid the extra allocation
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string

error: `format!(..)` appended to existing `String`
  --> src/fmt.rs:16:5
   |
16 |     result.push_str(&format!("{:indent$}", "", indent = indent));
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: consider using `write!` to avoid the extra allocation
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string

error: you are deriving `PartialEq` and can implement `Eq`
   --> src/node.rs:[37](https://github.com/kdl-org/kdl-rs/runs/7889199244?check_suite_focus=true#step:4:38)2:24
    |
372 | #[derive(Debug, Clone, PartialEq)]
    |                        ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
    |
    = note: `-D clippy::derive-partial-eq-without-eq` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
```

**Comment by CAD97** [comment]
Clippy has been appeased, I think.

**Comment by zkat** [comment]
released as part of kdl@4.4.0. Thanks.

**Pull request merged**
